### ISSUE TITLE
Laravel Start

### ISSUE THREAD

**Issue by htellez** [luckys/LaravelStart#2]
Buenas tardes desde Bogotá,Colombia, necesito ayuda con el siguiente tema,

estoy instalando este paquete pero cuando quiero hacer la migración me genera este erro y no se por donde buscar su respuesta.

gracias de antemano y felicitaciones por tan buena idea de tener un entorno listo para iniciar un proyecto

$ php artisan app:install
Running for module: dashboard
Migration table created successfully.
Nothing to migrate.
Running for module: auth
Migrated: 2015_06_01_164657_auth_setup_tables

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1139 Got error 'POSIX collating elements are not supported at offset 1' from regexp (SQL: SHOW TABLES WHERE Tables_in_soporte NOT REGEXP "[[.low
  -line.]]")

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1139 Got error 'POSIX collating elements are not supported at offset 1' from regexp

Héctor Téllez Arias

**Comment by luckys** [comment]
Hola Héctor, ese error seguro te sale porque no estas usando MySQL como base de datos, y al parecer esta línea que puse NOT REGEXP "[[.low-line.]]" solo es para MySQL, es algo que tengo arreglar. 
En caso de que estes usando mysql y te de ese error debe ser que tienes algo mal en el archivo .env o te falta algo porque deberia funcionar. Ese mismo error le ha dado a varias personas y es por lo que te comente mas arriba.
Para la próxima version espero tenerlo resuelto.
saludos!!

**Comment by htellez** [comment]
Hola caballero, gracias por la respuesta.

Te cuento que si estoy usando mysql como base de datos 
la base de datos se llama soporte y está creado con utf8_unicode_ci

Te anexo mi archivo .env

APP_ENV=local
APP_DEBUG=true
APP_KEY=SomeRandomString

DB_HOST=localhost
DB_DATABASE=soporte
DB_USERNAME=root
DB_PASSWORD=

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

Muchas gracias

**Comment by luckys** [comment]
Hola, prueba poniendo la base de datos como utf8_general_ci en vez de utf8_unicode_ci
saludos!!

**Comment by htellez** [comment]
Si señor eso y todo bien, gracias, ahora me generó este error

RuntimeException in EncryptionServiceProvider.php line 29:
No supported encrypter found. The cipher and / or key length are invalid.

**Comment by htellez** [comment]
Que pena mi hermano, ya encontré el problema.

No había generado el APP_KEY

MUCHAS GRACIAS

**Comment by luckys** [comment]
OK, me alegro que hayas resuelto el problema.

**Comment by htellez** [comment]
Caballero para molestarlo de nuevo.

tengo el siguiente error cuando quise hacer un rollback, me puedes ayudar?



vagrant@homestead:~/Sites/LaravelStart$ php artisan migrate:rollback


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Class 'AuthSetupTables' not found


de antemano muchas gracias

Héctor

2016-02-28 18:48 GMT-05:00 luckys_luck <notifications@github.com>:

**Comment by luckys** [comment]
Hola, el problema es que como la aplicación esta hecha usando el paquete pingpong-modules tienes que usar los comandos de ese paque, en la documentación estan [](https://sky.pingpong-labs.com/docs/2.1/modules)
en tu caso, el comando es este php artisan module:migrate-rollback
saludos

**Comment by htellez** [comment]
Listo mi hermano muchas gracias, si ese era mi problema,

**Comment by AsheDe** [comment]
Saludos, estoy intentando usar su proyecto para aprender laravel, y me abre la pagina del login pero no me permite entrar, aunque tengo el usuario creado en la BD. De hecho cree el usuario 

Admin | admin@demo.com | admin123     y me da  

Whoops! Error
El email o la contraseña no son correctos

que puede ser eso?? disculpe la molestia.
